name = "SoleAlphabets"
uuid = "bc461207-1577-452f-bfcc-57c11e9f51b7"
authors = ["Eduard I. STAN", "Giovanni PAGLIARINI"]
version = "0.1.0"

[deps]
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
SoleTraits = "f0cd7361-857b-4e5b-8aae-3a26fab9cfa9"

[compat]
IterTools = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
